const burgerData = [
  {
    id: 1,
    image: 'https://bit.ly/3ycm9Tk',
    name: 'Triple Cheeseburger',
    ingredients: 'PAN ESTILO BRIOCHE, 3 MEDALLONES DE 120 C/U (ROAST BEEF Y TAPA DE ASADO), DOBLE CHEDDAR, SALSA A BASE DE KEPTCHUP, PEPINILLOS ENCURTIDOS.',
    price: 900,
    stock: 10,
    category: 'burgers',
  },
  {
    id: 2,
    image: 'https://bit.ly/3KxlX3F',
    name: 'Doble Cheeseburger',
    ingredients: 'PAN ESTILO BRIOCHE, 2 MEDALLONES DE 120 C/U (ROAST BEEF Y TAPA DE ASADO), DOBLE CHEDDAR, SALSA A BASE DE KEPTCHUP, PEPINILLOS ENCURTIDOS.',
    price: 800,
    stock: 8,
    category: 'burgers',
  },
  {
    id: 3,
    image: 'https://bit.ly/39uQH8P',
    name: 'Simple Cheeseburger',
    ingredients: 'PAN ESTILO BRIOCHE, MEDALLON DE 120 C/U (ROAST BEEF Y TAPA DE ASADO), DOBLE CHEDDAR, SALSA A BASE DE KEPTCHUP, PEPINILLOS ENCURTIDOS.',
    price: 700,
    stock: 31,
    category: 'burgers',
  },
  {
    id: 4,
    image: 'https://bit.ly/3ycm9Tk',
    name: 'Triple Classic Burger',
    ingredients: 'PAN ESTILO BRIOCHE, 3 MEDALLONES DE 120 C/U (ROAST BEEF Y TAPA DE ASADO), DOBLE CHEDDAR, SALSA A BASE DE KEPTCHUP, PEPINILLOS ENCURTIDOS.',
    price: 900,
    stock: 6,
    category: 'burgers',
  },
  {
    id: 5,
    image: 'https://bit.ly/3KxlX3F',
    name: 'Doble Classic Burger',
    ingredients: 'PAN ESTILO BRIOCHE, 2 MEDALLONES DE 120 C/U (ROAST BEEF Y TAPA DE ASADO), DOBLE CHEDDAR, SALSA A BASE DE KEPTCHUP, PEPINILLOS ENCURTIDOS.',
    price: 800,
    stock: 8,
    category: 'burgers',
  },
  {
    id: 6,
    image: 'https://bit.ly/39uQH8P',
    name: 'Simple Classic Burger',
    ingredients: 'PAN ESTILO BRIOCHE, MEDALLON DE 120 C/U (ROAST BEEF Y TAPA DE ASADO), DOBLE CHEDDAR, SALSA A BASE DE KEPTCHUP, PEPINILLOS ENCURTIDOS.',
    price: 700,
    stock: 31,
    category: 'burgers',
  },
  {
    id: 7,
    image: 'https://bit.ly/3ycm9Tk',
    name: 'Triple Ajo Burger',
    ingredients: 'PAN ESTILO BRIOCHE, 3 MEDALLONES DE 120 C/U (ROAST BEEF Y TAPA DE ASADO), DOBLE CHEDDAR, SALSA A BASE DE KEPTCHUP, PEPINILLOS ENCURTIDOS.',
    price: 900,
    stock: 1,
    category: 'burgers',
  },
  {
    id: 8,
    image: 'https://bit.ly/3KxlX3F',
    name: 'Doble Ajo Burger',
    ingredients: 'PAN ESTILO BRIOCHE, 2 MEDALLONES DE 120 C/U (ROAST BEEF Y TAPA DE ASADO), DOBLE CHEDDAR, SALSA A BASE DE KEPTCHUP, PEPINILLOS ENCURTIDOS.',
    price: 800,
    stock: 8,
    category: 'burgers',
  },
  {
    id: 9,
    image: 'https://bit.ly/39uQH8P',
    name: 'Simple Ajo Burger',
    ingredients: 'PAN ESTILO BRIOCHE, MEDALLON DE 120 C/U (ROAST BEEF Y TAPA DE ASADO), DOBLE CHEDDAR, SALSA A BASE DE KEPTCHUP, PEPINILLOS ENCURTIDOS.',
    price: 700,
    stock: 31,
    category: 'burgers',
  },
  // {
  //   id: 4,
  //   image: 'https://bit.ly/3ONDYhs',
  //   name: 'Pizza Calabresa',
  //   ingredients: 'Con salame, queso, tomate, champiñones, aceitunas negras, cebolla, pimientos, pepinillos, salsa de tomate.',
  //   price: 930,
  //   stock: 10,
  //   category: 'pizzas',
  // },
  // {
  //   id: 5,
  //   image: 'https://bit.ly/3KtjJlT',
  //   name: 'Pizza Margarita',
  //   ingredients: 'Salsa, queso, tomate, champiñones, aceitunas negras, cebolla, pimientos, pepinillos, salsa de tomate.',
  //   price: 850,
  //   stock: 8,
  //   category: 'pizzas',
  // },
  // {
  //   id: 6,
  //   image: 'https://bit.ly/3vsTeZE',
  //   name: 'Pizza Anana',
  //   ingredients: 'Tomate, champiñones, aceitunas negras, cebolla, pimientos, pepinillos, salsa de tomate.',
  //   price: 720,
  //   stock: 3,
  //   category: 'pizzas',
  // },
  
]

export default burgerData